# Generated by Django 5.1.4 on 2025-09-09 15:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["priority", "due_date", "created_at"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Who is responsible for this task? (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                help_text="Set the priority level for this task",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="completed",
            field=models.BooleanField(
                default=False, help_text="Is this project completed?"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                help_text="Provide a detailed description of the project"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="When is this project expected to end? (optional)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                help_text="Enter a descriptive project name (minimum 3 characters)",
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="When did this project start?",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="completed",
            field=models.BooleanField(
                default=False, help_text="Is this task completed?"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Provide additional details about this task (optional)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text="When should this task be completed? (optional)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                help_text="Select the project this task belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                help_text="Enter a descriptive task title (minimum 3 characters)",
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
